title: krafterdev.xyz
description: "Krafter's little corner of the internet"
theme: jekyll-theme-midnight
markdown: GFM
show_downloads: false
github:
  is_project_page: false
plugins:
- jekyll-remote-theme
